### PR TITLE
Rename Dir.exists? to Dir.exist? to fix deprecation warning

### PR DESCRIPTION
**Pull request by bobrik**
```
warning: Dir.exists? is a deprecated name, use Dir.exist? instead
```

### CODE REVIEW

**Comment by untergeek** [comment]
LGTM™ and tests pass for me.

**Comment by untergeek** [comment]
Will you please bump the version in the gemspec file and add a matching blurb to the changelog?  I can merge these changes after that.

**Comment by bobrik** [comment]
Updated changelog, gemspec seems to be up to date already.

**Comment by untergeek** [comment]
You'll need to bump it to 2.2.3 as the currently published version is [2.2.2](https://rubygems.org/search?utf8=✓&query=logstash-output-file).  I do not know why the changelog has nothing for 2.2.2, but please add your changes for 2.2.3.

**Comment by bobrik** [comment]
Done

**Comment by untergeek** [comment]
Thanks! LGTM™

**Pull request closed without merging**
